### ISSUE TITLE
Cannot add widget to dashboard after installing!

### ISSUE THREAD

**Issue by normanhh3** [sdavis3/CodeCoverageDashboardWidgets#11]
Hi Folks,

For the life of me I can't seem to find the widget to add to the dashboard from my on-premise hosted TFS.

Is it possible that I'm using a version of TFS that is too old to work with this widget?

I am using TFS 2015 and the widget appears to have been installed correctly.  I have installed it into my Collection, just can't see it in the list of widgets to add to the dashboard.

I have successfully installed other third-party widgets before.

Any pointers would be helpful!

**Comment by sdavis3** [comment]
Theoretically, it should work according to the VSTS Team. I don't have an instance I can test with. Can you attach a couple screenshots of what you do see? Looking to see your installed extensions as well as your list of widgets from a dashboard (alphabetically it should show up as Code Coverage Widgets). Alternatively, you can also send them to my private email shane_b_davis at outlook dot com if you'd rather not post them here.

**Comment by normanhh3** [comment]
Here is the extension manager showing it is installed in my project collection.

![image](https://cloud.githubusercontent.com/assets/1637316/22797523/92356bc4-eecc-11e6-9a22-e3f611996374.png)

Here is the add widget dialog to select a widget from, and I can't find it available there at all!

![image](https://cloud.githubusercontent.com/assets/1637316/22797689/3c5dd9b0-eecd-11e6-86f7-5ee36d6fb98b.png)

Thoughts?

**Comment by sdavis3** [comment]
@normanhh3 I've connected with the VSTS Team to debug this. Which version of TFS2015 do you have installed? Update 1?

**Comment by sdavis3** [comment]
@normanhh3 Any response to this? the VSTS Team is awaiting our response so they can assist.

**Comment by normanhh3** [comment]
Hi man, sorry it has taken me so long to get back to you.

The version information I have from /tfs/_home/About shows version **14.95.25229.0**

**Comment by sdavis3** [comment]
@normanhh3 After conferring with VSTS team it appears you have TFS2015 Update 2.1. For dashboard widget support, Update 3 must be installed. If you are willing to upgrade, I would like to know if it works for you. Otherwise, I will wait a few days before closing this issue. Thank you for reporting it.

**Comment by normanhh3** [comment]
Well now, that is kind of annoying!  I will confer with our folks who
manage the box to see if we can get an upgrade done.

**Comment by sdavis3** [comment]
Closing this issue as dashboard widgets require TFS2015 Update 3 to be installed.
