### ISSUE TITLE
Please add code coverage analysis

### ISSUE THREAD

**Issue by NetTecture** [sdavis3/CodeCoverageDashboardWidgets#14]
Yeah, bigger, but...

I would love a way to drill into the code coverage similar to what we have in VS enterprise. WHich still is worth a premium due to the "in source code" visibility (which means you are limited to what VS can do down in the toolbox). Not everyone has VS Enterprise and particularly when you move online it is usefull to allow this information to go down into what stakeholders can possibly see (increase in code coverage, drilldown to particular sections of code based on namespace).

**Comment by sdavis3** [comment]
@NetTecture The scope of this widget is limited to what's available via the VSTS REST APIs. I can add the deltas (increases/decrease of code coverage), but drill down and other VS Enterprise features are not made available via the API today, that I'm aware of. 

How you would expect this experience to work via a widget interface?

**Comment by sdavis3** [comment]
Closing this item as out of scope.
