### ISSUE TITLE
Widgets stopped displaying results

### ISSUE THREAD

**Issue by EstateMaster** [sdavis3/CodeCoverageDashboardWidgets#22]
Our widgets have been working fine for months, however now they are appearing as blank widgets on our dashboards: https://www.screencast.com/t/msA9i7tq

I have checked the configuration, and they are all correctly set up: https://www.screencast.com/t/Vb21xHgqA9Li

The build results are showing code coverage data though? https://www.screencast.com/t/JIwysMVYMQpA 

Do you know what could be causing this?

**Comment by sdavis3** [comment]
I’m experiencing the same as of this morning. Let me reach out to the VSTS team to see if there are issues with the API.

**Comment by BoschM** [comment]
I've got the exact same problem

[https://www.screencast.com/t/fmmlgaco](https://www.screencast.com/t/fmmlgaco)

Recreating the widget doesn't help.

**Comment by sdavis3** [comment]
Thanks. I’ve reached out the VSTS team to see what the issue is. I suspect it’s an issue with the APIs.

**Comment by sdavis3** [comment]
Folks, I think we’ve resolved the issue. It was self-inflicted by a festering bug that I didn’t previously resolve. My apologies.

Your instances should now have the latest version 1.0.219 automatically. Can you please confirm it’s now working and report back?

**Comment by EstateMaster** [comment]
HI Shane

All works good now, thanks,

Regards,

Anthony

**Comment by d1820** [comment]
good now... thanks
