### ISSUE TITLE
Can we retrieve reports from SonarQube to this widget?

### ISSUE THREAD

**Issue by ankitaLath** [sdavis3/CodeCoverageDashboardWidgets#25]
I am looking for a widget as an extension to VSTS that can fetch the report generated by SonarQube and show in VSTS.

**Comment by sdavis3** [comment]
Thanks for your question. This widget only pulls data from the VSTS REST API. If it's not availble in the API, I'm unable to access it. There is already an extension for SonarQube at https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube
