### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by jka4cu** [sdavis3/CodeCoverageDashboardWidgets#27]
Trying to install on TFS 2017 Update 2.   I've downloaded the VSIX package and copied it to our TFS Application server. 
When I double click on the package to install it .. it returns the message "This extension is not installable on any currently installed products". 

What am I missing? Install log file attached. 

[VSIXInstaller_install_logfile.txt](https://github.com/sdavis3/CodeCoverageDashboardWidgets/files/2695514/VSIXInstaller_install_logfile.txt)

**Comment by sdavis3** [comment]
The log does not indicate that it’s finding your TFS instance. However, it does indicates it finds Visual Studio 2017 Enterprise. Are you confident you are running the install on the TFS instance directly?

**Comment by jka4cu** [comment]
Yes .. I am able to open the TFS Admin console on that machine.

**Comment by jka4cu** [comment]
If it helps the TFS 2017.2 instance is running on a Windwos Server 2012 R2 system.  
I"m logged in with the same account used to setup/install TFS Server. 
I have even tried running the vsix package from an "Adminstrative" command prompt.

**Comment by sdavis3** [comment]
The install package is created by Microsoft. I assume you have been able to successfully install other extensions using the same technique? I’m not sure if Windows Server 2012 would be a show-stopper.

**Comment by jka4cu** [comment]
To be honest this is the first extension I've tried to install against our TFS instance.

**Comment by sdavis3** [comment]
If you would, try to install a similar widget extension and also a completely different kind of extension to help narrow down the issue.

**Comment by sdavis3** [comment]
Any luck?

**Comment by jka4cu** [comment]
just tried to install the "Send Email Build and Release Task"  vsix package on our TFS 2017.2 on premise installation and I'm receiving the same error as when I try to install your package. 

can you please verify that product you are looking for in an On-premise installation?

**Comment by jka4cu** [comment]
Can you please verify if the on-premise TFS 2017 Update 2 is supported? If not what is the minimum version that is ?

**Comment by sdavis3** [comment]
While I have not personally tested it on TFS 2017, Microsoft requires at least TFS 2015 Update 3 or higher for folks using Team Foundation Server for widgets to function properly. Unfortunately, since you are experincing the same issue with other widgets, it would be difficult for me to troubleshoot likely not being caused by the CodeCoverageWidgets.
