### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by SychevIgor** [sdavis3/CodeCoverageDashboardWidgets#31]
Is it possible to show code coverage only for some branch?
In our project we are not running code coverage for Feature branches and as a result, quite frequently widget show - no data, but it means only one- latest build was done for feature branch.

It will be nice to have a dropdown with list of branches https://github.com/sdavis3/CodeCoverageDashboardWidgets/blob/master/configuration.html
and show code coverage only for this build (in our case - develop)

P.S. are you open to Pull Requests?

**Comment by sdavis3** [comment]
I am absolutely open to all pull requests! :)

**Comment by SychevIgor** [comment]
@sdavis3 which version of SDK you are using? I didn't understand it from source code or repository history
https://github.com/microsoft/azure-devops-extension-sdk
https://www.npmjs.com/package/azure-devops-extension-sdk

Probably, something like 2.0.4, but not sure

**Comment by SychevIgor** [comment]
Hmm
Based on API method signature - we can't pick coverage summary only for specific branch
Instead, we should find N and N-1 buildIDs and set both as parameters
![image](https://user-images.githubusercontent.com/578954/60772098-e02f2e00-a0f9-11e9-8ed6-0e2fae1947e4.png)

**Comment by SychevIgor** [comment]
Hmm.. looks like it was bad idea.
Shortly: 
If there are no completed builds- we can's choose all builds and select unique branch names.
Alternatively, we can find thousands of build results and it will be time/traffic expensive as well as filtering will be a nightmare. 
If we will load list of branches - we will can't setup for a not yet existing branch.

**Comment by SychevIgor** [comment]
Loos like it's a bit harder than I thought

**Comment by SychevIgor** [comment]
Created PR and closed it. maybe can be used in a future https://github.com/sdavis3/CodeCoverageDashboardWidgets/pull/32
But as of now- not ready to such deep digging
