### ISSUE TITLE
Display the build definition name on the widget 

### ISSUE THREAD

**Issue by kushaldwivedi** [sdavis3/CodeCoverageDashboardWidgets#5]
Similar to Release Definition Overview widget, if the build name can be displayed on the widget, it would help viewer to know the repository/build for which the code coverage is being displayed. Currently, only the one who has configured it would know about the build the code coverage is being displayed for.

**Comment by sdavis3** [comment]
Good idea. As a short term workaround, you could edit the title of the widget on the configuration page.
